### PR TITLE
Use correct API compatibility for OpenSSL dependency

### PR DESCRIPTION
**Pull request by arsonaut**
This fixes problem when OpenSSL dependency is overridden to version 1.1.

For example
```
D:> type ..\conanfile.txt
[requires]
libcurl/7.60.0@bincrafters/stable
# overrides
OpenSSL/1.1.0g@conan/stable
[generators]
cmake

D:> conan install ..
D:> cmake \projects\conan-libcurl\test_package\
D:> cmake --build .
```
will result in errors
```
  libcurl.lib(openssl.obj) : error LNK2019: unresolved external symbol _sk_num referenced in function _X509V3_ext [D:\tmp\conan-libcurl-test\build_test\test_package.vcxproj]
  libcurl.lib(openssl.obj) : error LNK2019: unresolved external symbol _sk_value referenced in function _X509V3_ext [D:\tmp\conan-libcurl-test\build_test\test_package.vcxproj]
...
  D:\tmp\conan-libcurl-test\build_test\bin\test_package.exe : fatal error LNK1120: 16 unresolved externals [D:\tmp\conan-libcurl-test\build_test\test_package.vcxproj]
```
because libcurl binary package from remote is used and that package was build with OpenSSL 1.0.2n

### CODE REVIEW

**Comment by SSE4** [comment]
@uilianries ping

**Comment by theirix** [comment]
@SSE4 @uilianries what do you think about this https://github.com/bincrafters/community/issues/346#issuecomment-410510700 ?

I am okay after this PR but looking after long-term solution with openssl.

**Comment by uilianries** [comment]
It's possible to solve it re-building libcurl overriding OpenSSL

    conan install .. --build libcurl

Just to have some idea, I tried on my environment (Linux + GCC8):

```
# conanfile.txt
[requires]
libcurl/7.60.0@bincrafters/stable
OpenSSL/1.1.0g@conan/stable
[generators]
cmake
```

    conan install .. --build libcurl
    conan info ..

my follow result:

```
libcurl/7.60.0@bincrafters/stable requirement OpenSSL/1.0.2n@conan/stable overriden by your conanfile to OpenSSL/1.1.0g@conan/stable 
PROJECT
    ID: 33df19d79f1499bc8c9cf416fe17b968ef531105
    BuildID: None
    Requires:
        libcurl/7.60.0@bincrafters/stable
        OpenSSL/1.1.0g@conan/stable
OpenSSL/1.1.0g@conan/stable
    ID: 35ea421ef4c1d32898da44c28e3cc900bc6459dc
    BuildID: None
    Remote: conan-center=https://conan.bintray.com
    URL: http://github.com/lasote/conan-openssl
    License: The current OpenSSL licence is an 'Apache style' license: https://www.openssl.org/source/license.html
    Recipe: Cache
    Binary: Cache
    Binary remote: conan-center
    Creation date: 2018-06-18 04:37:05
    Required by:
        libcurl/7.60.0@bincrafters/stable
        PROJECT
    Requires:
        zlib/1.2.11@conan/stable
libcurl/7.60.0@bincrafters/stable
    ID: 576875ac999f86555ad1463c0ff4d2a5caa74e89
    BuildID: None
    Remote: bincrafters=http://api.bintray.com/conan/bincrafters/public-conan
    URL: http://github.com/bincrafters/conan-libcurl
    License: MIT
    Recipe: Cache
    Binary: Cache
    Binary remote: bincrafters
    Creation date: 2018-06-07 08:57:40
    Required by:
        PROJECT
    Requires:
        OpenSSL/1.1.0g@conan/stable
        zlib/1.2.11@conan/stable
zlib/1.2.11@conan/stable
    ID: ec336a8e46e06995be9ad34dc1a7477dff42a7df
    BuildID: None
    Remote: conan-center=https://conan.bintray.com
    URL: http://github.com/lasote/conan-zlib
    License: http://www.zlib.net/zlib_license.html
    Recipe: Cache
    Binary: Cache
    Binary remote: conan-center
    Creation date: 2018-03-06 06:57:33
    Required by:
        libcurl/7.60.0@bincrafters/stable
        OpenSSL/1.1.0g@conan/stable
```

I think change the package id does not seem reasonable.

**Comment by SSE4** [comment]
I personally think proposed solution doesn't scale well - it has to be added to each recipe using OpenSSL.
there is article explaining things https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html
do I right understand from the article above that OpenSSL itself may be changed to use custom package id and it should solve the underlying problem?
/cc @lasote 

second point, it's probably not valid to use full version as package ID. I am pretty sure 1.1.0 and 1.0.2 are binary incompatible, while 1.0.2j and 1.0.2n should be fully binary compatible (not sure about 1.0.1 vs 1.0.2 though).

**Comment by arsonaut** [comment]
I think we have Conan design error here — as far as I understand, currently API/ABI compatibility can be tuned **only in downstream** packages.
I agree that such solution doesn't scale well — there should be possibility to do this in upstream packages also.

So probably we need to request an improvement on https://github.com/conan-io/conan/issues
Any suggestions?

**Comment by SSE4** [comment]
@arsonaut yes please, open an issue on conan bug-tracker.

**Comment by uilianries** [comment]
Since it is not a package problem, but a design flaw, I'm closing this PR.
